import {
  Component,
  ChangeDetectionStrategy,
  input,
  output,
  computed,
  inject,
} from '@angular/core';

import { NzTagModule } from 'ng-zorro-antd/tag';
import {
  ReportListItemViewModel,
  ReportListItemDisplayData,
  UUID,
} from '../../../../../types';
import { ReportListService } from '../../../../services/report-list.service';

/**
 * ReportListItem Component
 * Displays a single report row with formatted data.
 * Used as a cell template within ng-zorro table.
 *
 * This component is simplified when used with nz-table's column rendering.
 * It primarily handles click events and data display formatting.
 */
@Component({
  selector: 'app-report-list-item',
  standalone: true,
  imports: [NzTagModule],
  template: `<div class="report-item-row" (click)="onItemClick()">
    <!-- Content is rendered by table cells, but this component can be used standalone -->
    <ng-content></ng-content>
  </div>`,
  styleUrl: './report-list-item.component.scss',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class ReportListItemComponent {
  private readonly reportListService = inject(ReportListService);

  // Inputs
  item = input.required<ReportListItemViewModel>();
  index = input<number>(0);

  // Outputs
  clicked = output<UUID>();

  // Computed display data
  displayData = computed(() =>
    this.reportListService.transformToDisplayData(this.item())
  );

  /**
   * Handle item click - emit report ID
   */
  onItemClick(): void {
    this.clicked.emit(this.item().id);
  }

  /**
   * Get generated by label
   */
  getGeneratedByLabel(): string {
    return this.displayData().generatedByLabel;
  }

  /**
   * Get delivery channel label
   */
  getDeliveryChannelLabel(): string {
    return this.displayData().deliveryChannelLabel;
  }

  /**
   * Get delivery channel icon
   */
  getDeliveryChannelIcon(): string {
    return this.displayData().deliveryChannelIcon;
  }

  /**
   * Get delivery status label
   */
  getDeliveryStatusLabel(): string {
    return this.displayData().deliveryStatusLabel;
  }

  /**
   * Get delivery status color
   */
  getDeliveryStatusColor(): 'default' | 'success' | 'warning' | 'error' {
    return this.displayData().deliveryStatusColor;
  }

  /**
   * Get formatted date
   */
  getFormattedDate(): string {
    return this.displayData().createdAtFormatted;
  }
}
