import {
  Component,
  OnInit,
  AfterViewInit,
  ChangeDetectionStrategy,
  input,
  output,
  viewChild,
  ElementRef,
  signal,
  computed,
  inject,
} from '@angular/core';

import { NzSpinModule } from 'ng-zorro-antd/spin';
import { NzTagModule } from 'ng-zorro-antd/tag';
import {
  ReportListItemViewModel,
  ReportListItemDisplayData,
  UUID,
} from '../../../../../types';
import { ReportListService } from '../../../../services/report-list.service';
import { NzIconModule } from 'ng-zorro-antd/icon';

/**
 * ReportListComponent
 * Displays reports in an ng-zorro table with infinite scroll pagination.
 * Handles row rendering, pagination, empty states, and loading indicators.
 */
@Component({
  selector: 'app-report-list',
  standalone: true,
  imports: [NzSpinModule, NzTagModule, NzIconModule],
  templateUrl: './report-list.component.html',
  styleUrl: './report-list.component.scss',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class ReportListComponent implements AfterViewInit {
  private readonly reportListService = inject(ReportListService);

  // Inputs
  reports = input<ReportListItemViewModel[]>([]);
  isLoading = input<boolean>(false);
  isLoadingMore = input<boolean>(false);
  hasMore = input<boolean>(true);
  currentIndex = input<number>(0);

  // Outputs
  loadMore = output<void>();
  reportClick = output<UUID>();

  // Template reference
  scrollContainer = viewChild<ElementRef>('scrollContainer');

  // Local signals
  displayData = computed<ReportListItemDisplayData[]>(() =>
    this.reports().map(report =>
      this.reportListService.transformToDisplayData(report)
    )
  );

  // Computed properties
  isEmptyList = computed(
    () => !this.isLoading() && this.reports().length === 0
  );
  showNoMoreMessage = computed(
    () => !this.hasMore() && this.reports().length > 0 && !this.isLoadingMore()
  );

  // Table configuration
  columns = [
    { title: '#', width: '50px' },
    { title: 'Type', width: '100px' },
    { title: 'Date', width: 'auto' },
    { title: 'Channel', width: '100px' },
    { title: 'Status', width: '100px' },
  ];

  pageIndex = signal<number>(1);
  pageSize = signal<number>(20);

  constructor() {}

  ngAfterViewInit(): void {
    // Set up infinite scroll observer if needed
    this.setupInfiniteScroll();
  }

  /**
   * Setup infinite scroll detection
   */
  private setupInfiniteScroll(): void {
    const container = this.scrollContainer();
    if (!container) return;

    // Use Intersection Observer to detect when near bottom
    const observer = new IntersectionObserver(
      entries => {
        entries.forEach(entry => {
          if (entry.isIntersecting && this.hasMore() && !this.isLoadingMore()) {
            this.loadMore.emit();
          }
        });
      },
      {
        root: null,
        rootMargin: '200px',
        threshold: 0.1,
      }
    );

    // Observe a sentinel element for scroll trigger
    const sentinel = document.createElement('div');
    sentinel.className = 'scroll-sentinel';
    container.nativeElement.appendChild(sentinel);
    observer.observe(sentinel);
  }

  /**
   * Handle table row click
   */
  onRowClick(reportId: UUID): void {
    this.reportClick.emit(reportId);
  }

  /**
   * Format date for display
   */
  formatDate(date: Date | string): string {
    if (typeof date === 'string') {
      date = new Date(date);
    }
    return this.reportListService.formatDate(date);
  }

  /**
   * Get generated by label
   */
  getGeneratedByLabel(generatedBy: string): string {
    return generatedBy === 'scheduled' ? 'Scheduled' : 'On-Demand';
  }

  /**
   * Get generated by badge color
   */
  getGeneratedByColor(generatedBy: string): string {
    return generatedBy === 'scheduled' ? 'blue' : 'orange';
  }

  /**
   * Get delivery channel label
   */
  getDeliveryChannelLabel(channel: string): string {
    return channel === 'email' ? 'Email' : 'In-App';
  }

  /**
   * Get delivery channel icon
   */
  getDeliveryChannelIcon(channel: string): string {
    return channel === 'email' ? 'mail' : 'notification';
  }

  /**
   * Get delivery status color
   */
  getStatusColor(status: string): 'default' | 'success' | 'warning' | 'error' {
    const colorMap: Record<
      string,
      'default' | 'success' | 'warning' | 'error'
    > = {
      queued: 'default',
      sent: 'success',
      opened: 'warning',
    };
    return colorMap[status] || 'default';
  }

  /**
   * Get delivery status label
   */
  getStatusLabel(status: string): string {
    const labels: Record<string, string> = {
      queued: 'Queued',
      sent: 'Sent',
      opened: 'Opened',
    };
    return labels[status] || status;
  }

  /**
   * Track by function for ngFor
   */
  trackByReportId(index: number, report: ReportListItemViewModel): string {
    return report.id;
  }
}
